featured_categories:
  type: list
  list_type: category
  default: ""
category_1_short_description:
  default: ""
  description: 
    en: "description for featured category card 1"
category_2_short_description:
  default: ""
  description: 
    en: "description for featured category card 2"
category_3_short_description:
  default: ""
  description: 
    en: "description for featured category card 3"
category_4_short_description:
  default: ""
  description: 
    en: "description for featured category card 4"
