featured_categories:
  type: list
  list_type: category
  default: ""
category_short_description:
  type: list
  default: ""
  description: 
    en: "semicolon delimited, in this order: category_id;shortdescription"
